---
# Enable systemd services and timers

- name: Enable system services
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ system_services }}"
  tags:
    - services

- name: Enable system timers
  become: true
  systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop: "{{ system_timers }}"
  tags:
    - services
